services:
   wordpress:
     image: wordpress:latest
     container_name: kactus-web
     networks:
       - kactus-public
       - kactus-private
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: kactus-bdd
       WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
       WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
     volumes:
       - /opt/kactus/kactus-web/wp-content/themes/Kactus:/var/www/html/wp-content/themes/Kactus
       - /opt/kactus/kactus-web/wp-config.php:/var/www/html/wp-config.php

networks:
  kactus-public:
    external: true
  kactus-private:
    external: true
