services:
   web:
     image: phpipam/phpipam-www:latest
     networks:
       - kactus-network
     ports:
       - "8080:80"
     environment:
       - TZ=Europe/London
       - IPAM_DATABASE_HOST=db-ipam
       - IPAM_DATABASE_PASS=aucuneidee
       - IPAM_DATABASE_WEBHOST=%
     restart: unless-stopped
     volumes:
       - phpipam-logo:/phpipam/css/images/logo
       - phpipam-ca:/usr/local/share/ca-certificates:ro
     depends_on:
       - db-ipam
     cap_add:
       - NET_ADMIN
       - NET_RAW

   cron:
     image: phpipam/phpipam-cron:latest
     networks:
       - kactus-network
     environment:
       - TZ=Europe/London
       - IPAM_DATABASE_HOST=db-ipam
       - IPAM_DATABASE_PASS=aucuneidee
       - SCAN_INTERVAL=1h
     restart: unless-stopped
     volumes:
       - phpipam-ca:/usr/local/share/ca-certificates:ro
     depends_on:
       - db-ipam
     cap_add:
       - NET_ADMIN
       - NET_RAW

   db-ipam:
     image: mariadb:latest
     networks:
       - kactus-network
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     restart: unless-stopped
     volumes:
       - phpipam-db-data:/var/lib/mysql

volumes:
   phpipam-db-data:
   phpipam-logo:
   phpipam-ca:

networks:
  kactus-network:
    external: true
