services:
   web:
     image: phpipam/phpipam-www:v1.7.0
     networks:
       - kactus-public
       - kactus-private
     ports:
       - "8181:80"
     environment:
       - TZ=Europe/Paris
       - IPAM_DATABASE_HOST=kactus-bdd
       - IPAM_DATABASE_PASS=${MYSQL_ROOT_PASSWORD}
       - IPAM_DATABASE_WEBHOST=%
     restart: unless-stopped
     volumes:
       - phpipam-logo:/phpipam/css/images/logo
       - phpipam-ca:/usr/local/share/ca-certificates:ro
     cap_add:
       - NET_ADMIN
       - NET_RAW

   cron:
     image: phpipam/phpipam-cron:v1.7.0
     networks:
       - kactus-public
       - kactus-private
     environment:
       - TZ=Europe/Paris
       - IPAM_DATABASE_HOST=kactus-bdd
       - IPAM_DATABASE_PASS=${MYSQL_ROOT_PASSWORD}
       - SCAN_INTERVAL=1h
     restart: unless-stopped
     volumes:
       - phpipam-ca:/usr/local/share/ca-certificates:ro
     cap_add:
       - NET_ADMIN
       - NET_RAW

volumes:
   phpipam-logo:
   phpipam-ca:

networks:
  kactus-public:
    external: true
  kactus-private:
    external: true
