services:
  kactus-intra:
    build: .
    container_name: kactus-intra
    image: kactus-intra:latest
    restart: unless-stopped
    networks:
      - kactus-public
    ports:
      - "8081:80"

networks:
  kactus-public:
    external: true