services:
  kactus-intra:
    build: .
    container_name: kactus-intra
    image: kactus-intra:latest    
    restart: unless-stopped
    networks:
      - kactus-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.intranet.rule=Host(`intranet.portainer.kactus.guillaume-sanchez.fr`)"
      - "traefik.http.routers.intranet.entrypoints=web"
      - "traefik.http.services.intranet.loadbalancer.server.port=80"

networks:
  kactus-network:
    external: true