services:
  grafana:
    image: grafana/grafana:12.1.0
    restart: unless-stopped
    networks:
      - kactus-monitoring
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - loki

  loki:
    image: grafana/loki:3.5.0
    networks:
      - kactus-monitoring
    restart: unless-stopped
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:v3.1.0
    networks:
      - kactus-monitoring
    volumes:
      - "/opt/kactus/grafana/prometheus-config.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090

  promtail:
    image: grafana/promtail:3.5.0
    networks:
      - kactus-monitoring
    restart: unless-stopped
    volumes:
      - /var/log:/var/log
      - /opt/kactus/grafana/promtail-config.yml:/etc/promtail/config.yml

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - kactus-monitoring
    ports:
      - 8080:8080

volumes:
  grafana_data:

networks:
  kactus-monitoring:
    external: true
