services:
  traefik:
    image: traefik:v3.0
    container_name: kactus-traefik
    restart: unless-stopped
    command:
      # Active le Dashboard (interface visuelle) sans mot de passe (ok car derrière ton firewall)
      - "--api.insecure=true"
      # Active le fournisseur Docker (pour écouter les autres conteneurs)
      - "--providers.docker=true"
      # Sécurité : N'expose pas les conteneurs par défaut (il faudra mettre un label)
      - "--providers.docker.exposedbydefault=false"
      # Définit le point d'entrée "web" sur le port 80 interne du conteneur
      - "--entrypoints.web.address=:80"
    ports:
      # C'EST ICI QUE ÇA SE JOUE :
      # Ton NPM envoie sur le port 82, donc on ouvre le 82 sur le serveur
      # et on le redirige vers le 80 de Traefik.
      - "82:80"
      # Le port pour accéder au Dashboard d'administration de Traefik
      - "8282:8080"
    volumes:
      # Indispensable : Donne accès à Traefik pour "voir" les autres conteneurs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - kactus-network

networks:
  kactus-network:
    external: true