services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.39.1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - kactus-monitoring
    ports:
      - 9000:9000
      - 8000:8000

volumes:
  portainer_data:
    name: portainer_data

networks:
  kactus-monitoring:
    external: true